sudo: false

language: go

# Don't email me the results of the test runs.
notifications:
  email: false

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...

env:
  - GO111MODULE=on

install: true