language: go

go:
  - 1.8.x
  - tip

addons:
   apt:
      packages:
         - libx11-dev xorg-dev
         - libxtst-dev libpng++-dev
         - xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
        #  - libusb-dev
         - libxkbcommon-dev
         - xsel
         - xclip

before_install:
  - go get -t -v ./...

script:
  - go test -v -failfast -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)